### ISSUE TITLE
Feature request: Show all pools of all platforms and filter them

### ISSUE THREAD

**Issue by cryptotester** [vfat-tools/vfat-tools#102]
Hi, it would be cool -since you seem to have everything in place already- to show (maybe make a new page for this feature) all pools of all platforms in one single page, then let the user sort them (asc/desc) by APY, coin etc. filter them vault type, e.g. by single asset, stables LPs, stables etc.

See filter on https://app.beefy.finance/ for inspiration:

![image](https://user-images.githubusercontent.com/49552918/110245425-5df8ac00-7f63-11eb-9d5d-7b53b62b83b7.png)

Filter by platform (multi drop down select so to allow selecting several ones at once, e.g. the ones the user likes the most).
More filters can be welcome too, e.g. show only farms where APY e.g. is > 40% or so, so to avoid scrolling for non profitable ones.

**Comment by vfat-tools** [comment]
This would be great of course but is a huge task, it requires redesigning every page and would load very slowly with the current code (which reads everything on the spot off the chain). Still it is definitely in the broader roadmap.

**Comment by cryptotester** [comment]
The logic should not belong to the page (view) I was thinking that every page has a method in the backend to be called and get the results. I didn't check the code, but if it's like that, in theory it would be possible to leave all pages as is, create a new page that calls the main "populate" of each website and then group all results in one single json with everything. Then parse it in a new page. I'd also suggest to cache (e.g. make a request every 15 mins) those results of course, maybe run this on your side and save the results in a DB. That would allow also in the future to make fancy reports showing e..g. TVL going up / down in time, showing APY going up and down etc. (and this would be a different request of course, but just to say it can be useful to store data instead of (slowly) fetching it from the blockchain all the time.

**Comment by vfat-tools** [comment]
There is no backend at all, the information is loaded client-side using the user's Metamask connection. So, it requires writing a backend first.
________________________________
