### ISSUE TITLE
Add BondAppetit to vfat.tools

### ISSUE THREAD

**Issue by bondappetitprotocol** [vfat-tools/vfat-tools#1029]
BondAppetit is a DeFi protocol for business loans with a stablecoin fully backed by real-world assets with fixed periodic income (bonds).

Website: https://bondappetit.io
Telegram: https://t.me/BondAppetitEn

**Comment by vfat0** [comment]
did you check? https://vfat.tools/bondappetit/

**Comment by bondappetitprotocol** [comment]
Add this contract please: 0x969c70f75aecb0decbde0554fb570276c9a85751

**Comment by vfat0** [comment]
please consider a pull request, should be easy to modify

**Comment by Dimosgr** [comment]
This address has been added please check https://vfat.tools/bondappetit/
