### ISSUE TITLE
Query - dose all the pools supported in https://vfat.tools/ have same logic?

### ISSUE THREAD

**Issue by huahuayu** [vfat-tools/vfat-tools#104]
Hi, I saw you support Big Data Protocol pool yield dashboard, I am curious about whether the pool you supported have the same yield farm logic( or in other words, the same forked codebase), so it's easy to add a new one.  Or do they have significant difference, every protocol need a separate logic to handle?

I am going to research big data protocol smart contract, if it's forked from a well-known protocol, then I will have more confidence in it. That's why I ask.

**Comment by vfat-tools** [comment]
It is the same codebase as Sushi, Pickle, etc (MasterChef based).
________________________________

**Comment by huahuayu** [comment]
so who's the creator of the MasterChef contract?
