### ISSUE TITLE
Add polyfrenchie

### ISSUE THREAD

**Issue by polyfrenchie** [vfat-tools/vfat-tools#1040]
Polyfrenchie Finance is a decentralized multichain farm yield project running on Binance Smart Chain and Polygon.

Website: https://polyfrenchie.com/

Contracts: 

pFRE:
Polygon: 0xb82bC28678e9796C282E24a2D0383aD6BFf1d2Cb
BSC: 0xf6A05aFD4665392F066289dC7eff4A195825e8dA

Masterchef:
Polygon: 0xF85F239B155D8B9f289e69A658611d8C2EaCE9f8
BSC: 0x8fe1601b8392eeC32add08b66e930Dcd3433e1CA

**Comment by vfat0** [comment]
please consider a pull request, should be straightforward (instructions in the readme)
