### ISSUE TITLE
#request Add https://polycuppa.finance/ the next layer of polymocha over polygon matic

### ISSUE THREAD

**Issue by polymocha** [vfat-tools/vfat-tools#1042]
Cuppa - 0xCB0bCBe3C0bD963f549480C2D052024db68aDEfB
Cuppa MasterChef - 0x95FDc452152bd606F3c9B7d5c744a551A86b2520

Polygon Block Countdown - https://polygonscan.com/block/countdown/16675000

Thankyou :)

**Comment by vfat0** [comment]
please consider a pull request, should be straightforward (instructions in the readme)

**Comment by jambestwick** [comment]
@polymocha , add by youself
