### ISSUE TITLE
ShibaSwap "Bone" price is not updating and is constantly listing at 15.50 which is leading to erroneous APR

### ISSUE THREAD

**Issue by sumfattytuna** [vfat-tools/vfat-tools#1044]
The BONE price seems to be stuck at 15.50 for shibaswap which is making the APR/ rewards go crazier than they seem.  Would also be nice to see functionality that includes lock up for coins like these that have reward lockups.

**Comment by vfat0** [comment]
Thank you for the report, unfortunately this is due to the coingecko price being stuck there https://www.coingecko.com/en/coins/bone-shibaswap, I'll see about a workaround

**Comment by sumfattytuna** [comment]
Cheers, appreciate all your hard work
