### ISSUE TITLE
Add Valuse Set Dollar (VSD)

### ISSUE THREAD

**Issue by vsd-media** [vfat-tools/vfat-tools#105]
**Link:** https://valueset.finance/

**Info:** Value Set Dollar (VSD) is an algorithmic and partially collateral stablecoin that incorporates key features from ESD V2, BASIS, and FRAX. It aims to solve core issues that its predecessors have struggled.

**Github:** https://github.com/vsdcrew/dollar

**Audit:** Audited by Peckshield in February 2021

**Comment by vfat-tools** [comment]
are you guys able to do a pull request for this?
________________________________

**Comment by vsd-media** [comment]
Yes, did you merge our PR?

Btw, here is our audit from Pecksheild, thanks.
https://github.com/peckshield/publications/blob/master/audit_reports/PeckShield-Audit-Report-VSD-v1.0.pdf

**Comment by vfat-tools** [comment]
Did you submit one? :)

**Comment by vsd-media** [comment]
Oh wait, not yet. 

What pull request do I submit? Is there a format?
Thanks

**Comment by vfat-tools** [comment]
To do a pull request you have to fork the repo and write the code to display your project's page, by copying existing code and making adjustments (e.g. in your case checking out the esd.js, basis.js, frax.js files). I can help your dev do this just message me on TG.

**Comment by vsdcrew** [comment]
Thanks!
Any instructions on running a server locally? I got the following error when access any project while server running with dev script: 
Error: too many arguments: passed to contract (count=2, expectedCount=1, code=UNEXPECTED_ARGUMENT, version=contracts/5.0.12)
ethers_helper.js:1125 Couldn't match 0x... to any known token type.
Thanks

**Comment by vfat-tools** [comment]
Nothing special no maybe you are on the wrong network? You can message me on TG if you want @vfat0

**Comment by vsdcrew** [comment]
Thanks! Had ping you on TG.

**Comment by vsdcrew** [comment]
Caused by a breaking change of ethcall BTW.

**Comment by vsdcrew** [comment]
Hi, 
VSD scripts PR submitted: https://github.com/vfat-tools/vfat-tools/pull/146.
Thanks

**Comment by vfat-tools** [comment]
Excellent thank you guys! Unfortunately the front page is currently reserved for the biggest projects (e.g. >25M TVL) so its not on there, but vfat.tools/vsd looks good.
