### ISSUE TITLE
Issues with polygon.beefy.finance

### ISSUE THREAD

**Issue by mike503** [vfat-tools/vfat-tools#1058]
https://vfat.tools/polygon/beefy/

It's missing some of the pools, and it's not displaying data like all the other farms I've used vfat for. Not sure if that is on purpose(?) - I'd expect to still be able to get an APR or something, even if there isn't a direct reward token since it's autocompounded.

Either way, still missing pools like BONE-USDC QLP (basically all the BONE ones, for sure are missing)

**Comment by vfat0** [comment]
we do not show APY on autocompounding pools yes, and because they are constantly updating their pools it is difficult to keep the site accurate, it would have to be submitted via them, Koge does this for instance
