### ISSUE TITLE
Wrong APR of MidasGold

### ISSUE THREAD

**Issue by thanhnguyennguyen** [vfat-tools/vfat-tools#108]
Hello @vfat-tools @vfatouros 
APR of MidasGold is wrong
https://midasgold.network/farms

**Comment by thanhnguyennguyen** [comment]
We are calculating APY (for year). So we should include all pendingReward. Because after one month, one year, all rewards are unlocked

**Comment by vfat-tools** [comment]
Looking into this

**Comment by vfat-tools** [comment]
Fixed, thank you
