### ISSUE TITLE
Listing on VFAT Tools

### ISSUE THREAD

**Issue by SobaSwap** [vfat-tools/vfat-tools#1142]
Hi, how do I get listed on VFAT Tools? Appreciate if someone could share the process of doing so for new farms. Thank you!

**Comment by vfat0** [comment]
hello, submitting a pull request would be the most direct way, alternatively you can share your url and farm contract here and be added to the queue

**Comment by SobaSwap** [comment]
Hi, Requesting to add SobaSwap onto vfat-tools please.  Website: https://sobaswap.finance/Masterchef: 0x04C5631AE849577D4C4D9eB161ef740d9b8FF13FToken Address: 0x940aAE22d8Ea74C347Df8F057aec57A84a21ac46 Thank you! Best regards,SobaSwap From: vfatSent: Monday, 19 July 2021 2:57 AMTo: vfat-tools/vfat-toolsCc: SobaSwap; AuthorSubject: Re: [vfat-tools/vfat-tools] Listing on VFAT Tools (#1142) hello, submitting a pull request would be the most direct way, alternatively you can share your url and farm contract here and be added to the queue—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SobaSwap** [comment]
Requesting to add SobaSwap onto vfat-tools please. 

Website: https://sobaswap.finance/
Masterchef: 0x04C5631AE849577D4C4D9eB161ef740d9b8FF13F
Token Address: 0x940aAE22d8Ea74C347Df8F057aec57A84a21ac46

**Comment by SobaSwap** [comment]
Hi, how's the progress of this? Do you need any further information from us? Happy to provide if needed. Thanks!

Requesting to add SobaSwap onto vfat-tools please.

Website: https://sobaswap.finance/
Masterchef: 0x04C5631AE849577D4C4D9eB161ef740d9b8FF13F
Token Address: 0x940aAE22d8Ea74C347Df8F057aec57A84a21ac46

**Comment by Dimosgr** [comment]
Hello, the url that you have provided, does not work.

**Comment by Dimosgr** [comment]
closed because there is no response
