### ISSUE TITLE
Input wallet address

### ISSUE THREAD

**Issue by Akshaygit1** [vfat-tools/vfat-tools#1147]
Is it possible to enter wallet address manually and get details? (without connecting)
I usually use smartphones and unable to use metamask, it would be great if i just enter my wallet address and get farming info.
Thanks.

**Comment by vfat0** [comment]
that's not possible without a connection, but there are ways for it to work on mobile (metamask mobile browser, walletconnect). you can check any address by appending ?addr=0x123 to the url

**Comment by Dimosgr** [comment]
closed because there is no response
