### ISSUE TITLE
Please add AstroProtocol

### ISSUE THREAD

**Issue by laikatospace** [vfat-tools/vfat-tools#1164]
I tried pulling, editing and requesting a push on the repo, but the js logic breaks when I attempt to implement for Astro.

Astros' MasterChef: 0x4b37545712303738AC518dd9717A47F918565894
https://astroprotocol.com

Thank you!

**Comment by Dimosgr** [comment]
Added

**Comment by laikatospace** [comment]
Hi Dimosgr, last minute change;

Can we update the MasterChef address to:
0x91bf510087030741CdF83aC0cec3624199241a93

**Comment by Dimosgr** [comment]
sure. I have just updated.

**Comment by laikatospace** [comment]
Final update, due to issues with the previous MasterChef contract... Please update:

Token contract: 0x9Fe424c2B6047b86B237bA00f656d5e268246CA2
MasterChef contract: 0x4e4eFBA98C4b7441e257019bD06069889571f88E

**Comment by Dimosgr** [comment]
Updated, please wait until it showed up.
