### ISSUE TITLE
#request please add https://volcano.exchange/ over polygon scan

### ISSUE THREAD

**Issue by Volcanoexchange** [vfat-tools/vfat-tools#1178]
LAVA - 0x851795f15bC0ce3fA58540D98201E117a4bDf41a
MC - 0xCDf9B58386DDFAba579C123CbFC4375cfB603188

**Comment by arya09021998** [comment]
CAN YOU PLEASE ADD THIS

**Comment by Dimosgr** [comment]
Hello, the url that you have provided, does not work.

**Comment by Dimosgr** [comment]
closed because there is no response
