### ISSUE TITLE
Please add https://restaurantdefi.finance/

### ISSUE THREAD

**Issue by restaurantdefi** [vfat-tools/vfat-tools#1182]
+Contract address: https://bscscan.com/address/0x6826DdFD0fefB094F298a85c92FbbfCcaB0B3e8E
+MasterChef: https://bscscan.com/address/0x81BcAcAA5fCBA74212d82101160fc9369E38213d

**Comment by jambestwick** [comment]
do you need help ? vatalikbuterin.eth
