### ISSUE TITLE
Iridium Finance issues

### ISSUE THREAD

**Issue by polydaedalus** [vfat-tools/vfat-tools#1201]
Hello! So the page for iridium finance was created and added, but it wasn't added to the Polygon list of farms. Also, it isn't showing all pools correctly, PID 0 should be IRID-PLATIN, 1 should be IRID-USDC, 2 should be IRID-WMATIC, and 3 should be PLATIN-USDC. Also, there's a pool incorrectly showing NaN%. Please revise, thanks!

https://vfat.tools/polygon/iridiumfinance/

**Comment by vfat0** [comment]
the pull request had not been tested locally then. please make the required changes, test them locally, and submit a new pull request
