### ISSUE TITLE
add Avengers DeFi on vfat.tools Polygon

### ISSUE THREAD

**Issue by pedrowithwings** [vfat-tools/vfat-tools#1248]
Hello, I've found a new project on Polygon. Could you please check and add it?
https://avengersdefi.club/
https://t.me/avengers_defi_club
https://twitter.com/avengers_defi

0x9dfb228e6eeed1667a044b7e1465bd920822e501
0x7b6c8EF21537950e309c093C9C96B6558cc6550c
0xA54c2C322b63ac96ED4376798dA301a2c69B46b7

**Comment by Dimosgr** [comment]
Added
