### ISSUE TITLE
PolyFund VFat listing 

### ISSUE THREAD

**Issue by PolyFundDevs** [vfat-tools/vfat-tools#1253]
Please add PolyFund to VFAT
https://www.polyfund.finance/
https://t.me/polyfund

Token Contract

FUND Token 0x4B0F2dA2c4E7CC60f3b918461Ec4f16cCc974622

Chef Contract

MasterChef 0xdA30Aae916417C9Ad8DE97Bb1d59395f2Dd905e4

Native Vault Contract

Auto FUND 0xdcfd912b50904B4d5745DfFe0D4d7a5097c82849

**Comment by Dimosgr** [comment]
Added
