### ISSUE TITLE
Please add OKex Chain: Kswap, PandaSwap and CherrySwap

### ISSUE THREAD

**Issue by muise123** [vfat-tools/vfat-tools#1271]
Kswap: https://app.kswap.finance/#/farm/liquidity

PandaSwap: https://app.pandaex.org/#/farm

CherrySwap: https://www.cherryswap.net/farms/

**Comment by jambestwick** [comment]
@muise123 need masterchef address and  token address

**Comment by Dimosgr** [comment]
I have added kswap and cherryswap. Need to wait for pandaswap in order to receive their contract.

**Comment by jambestwick** [comment]
> I have added kswap and cherryswap. Need to wait for pandaswap in order to receive their contract.

I dont know  how you can  find the masterchef ?

**Comment by Dimosgr** [comment]
in order to do this the project has to started first.

**Comment by muise123** [comment]
awesome, thanks. when will they appear on the vfat.tools sites?

**Comment by muise123** [comment]
PandaSwap: https://app.pandaex.org/#/farm is live now

**Comment by Dimosgr** [comment]
I need the staking address in order to add it and the aprove button in the site does not work in order to see it. If you have the contract address that would be very helpful.

**Comment by Dimosgr** [comment]
I have managed to find the address but the contract is not verified and I cant read the code.
