### ISSUE TITLE
https://app.moontography.com/#/faas

### ISSUE THREAD

**Issue by pdr76** [vfat-tools/vfat-tools#1313]

**Comment by Dimosgr** [comment]
Hello, I'm trying to add it to all chains, nevertheless, the contracts are not verified and I cant read the code.
https://etherscan.io/address/0x34b2241c11db9a817d483886A53d91D8E1D6C006#code
https://bscscan.com/address/0x57aAb57A79663E4a4a7f1bC9155884b160F0Ac95#code
https://polygonscan.com/address/0x6A46Cf7F40f4ed7E997FeC79E9b8f2e3E3348f93#code
