### ISSUE TITLE
Sushi on Harmony

### ISSUE THREAD

**Issue by ionush** [vfat-tools/vfat-tools#1317]
Problem on the sushi calc on harmony. Receive this error message.

Thanks for all the hard work!

![image](https://user-images.githubusercontent.com/26359601/127966132-a5cff3d8-3546-4ce1-b078-3dd9b294a3fc.png)

**Comment by ionush** [comment]
still error but new message:

![image](https://user-images.githubusercontent.com/26359601/127976529-e3d24f73-8267-4a2b-9bb6-792978cafc65.png)

**Comment by Dimosgr** [comment]
Hello, I have just updated and copy the abi from the explorer again. It works for me, please check again when my update passed to the server.
