### ISSUE TITLE
Issues with ShibaSwap on Fantom

### ISSUE THREAD

**Issue by ShibaFantom** [vfat-tools/vfat-tools#1329]
When reading the MasterChef contracts for both ShibaSwap - GBONE and ShibaSwap - BONE I get the error:

*************** 👨‍🌾 UNOFFICIAL ShibaSwap FARMING CALCULATOR 👨‍🌾 ***************
INFO  : https://shibafantom.finance
******************************************************************************

Wed Aug 04 2021 08:44:18 GMT-0500 (Central Daylight Time)

[CHANGE WALLET] -=- [CLEAR BROWSER STORAGE]

Initialized 0x6eb3095c9190d5831ff03a1acf4c5f523c74df3d

Reading smart contracts...

{}
Oops something went wrong. Try refreshing the page.

**Comment by Dimosgr** [comment]
Updated both. Please wait for the next update to see them.
