### ISSUE TITLE
BSC Zoofarm.app not including Key (reward price)

### ISSUE THREAD

**Issue by varut** [vfat-tools/vfat-tools#1334]
![image](https://user-images.githubusercontent.com/4160772/128286948-53477bd1-53be-407c-9b3c-b315b2619f03.png)

Key Contact address 0x6652462466dcee5cb1dda95379fae3c3e57f6719

Charts https://dex.guru/token/0x6652462466dcee5cb1dda95379fae3c3e57f6719-bsc

**Comment by Dimosgr** [comment]
There is no way to obtain its price because its not in coingecko or in any staking pool.
