### ISSUE TITLE
List PolyShield.Finance

### ISSUE THREAD

**Issue by polyshield-finance** [vfat-tools/vfat-tools#1358]
https://polyshield.finance

Verified Contracts:
Polyshield: https://polygonscan.com/address/0xf239e69ce434c7fb408b05a0da416b14917d934e
MasterChef: https://polygonscan.com/address/0x0Ec74989E6f0014D269132267cd7c5B901303306

Let me know if you need something else?

Note: 
It's not clear from the readmen what changes are needed in a pull request.

Thanks,

**Comment by Dimosgr** [comment]
Added. Please wait for the next update.
