### ISSUE TITLE
Site breaking from Metamask update

### ISSUE THREAD

**Issue by dcFX0** [vfat-tools/vfat-tools#1367]
The current update of Metamask (version 9.0.0) broke a number of web3 sites including vfat-tools.

`We noticed that the current website tried to use the removed window.web3 API. `

related to this:
https://medium.com/metamask/no-longer-injecting-web3-js-4a899ad6e59e

**Comment by vfat0** [comment]
I haven't been able to reproduce this, can you send a console log by any chance?
