### ISSUE TITLE
Add farm for BURP

### ISSUE THREAD

**Issue by steao** [vfat-tools/vfat-tools#1417]
To the Aggregator of Aggregators and the Fattiest of Vs,

I would be forever grateful if someone could add the new farm for CoinBurp ($BURP).

CoinBurp main URL: 
https://coinburp.com

Farm URL:
https://burptoken.com/stake

Staking Address:
https://etherscan.io/address/0xf945789d494fbb3c859478dcb7c86493f31a5dd4

CoinBurp Repo: https://github.com/coinburp
Token Address: https://etherscan.io/token/0x33f391f4c4fe802b70b77ae37670037a92114a7c

Thank you very much,

-SteAO

**Comment by vfat0** [comment]
sorry I didn't get back to you on this, due to the contracts being non-standard it has to be submitted via pull request please
