### ISSUE TITLE
How to handle non-native token data errors (Polygon)

### ISSUE THREAD

**Issue by WombatFromHell** [vfat-tools/vfat-tools#1493]
I've been tracking an issue with partnered tokens on some MasterChef contracts not fetching price and TVL data correctly which leads to NaN for all APR estimates. The only workaround I've found is if there's an LP pair containing a known token (like WMATIC or USDC) to match with the unknown token on the MasterChef and plugging the index of that LP into the `deathPoolIndices` parameter on the `loadMaticChefContract(...)` function. This fix doesn't help with tokens that don't have an LP pair on the MC.

Any ideas on how to workaround or fix this issue without committing fixes to core VFAT functions? It seems some farms write their own contract loading function to side-step the issue for more complex farm behavior (like being rewarded with multiple different native tokens), but I've not seen any examples of how to do this for partnered tokens with no known LP pair. Any advice on this issue would be much appreciated.

**Comment by Dimosgr** [comment]
Hi. Yes, if the token has a price at coingecko you can use this array in order to receive the price from there. You have to add the id, the symbol and the address of the token. These arrays are on every helpers files for all chains. Here is an example for bsc.

![image](https://user-images.githubusercontent.com/36194185/130315928-1e7154de-5e99-4894-a99b-1b3bbb637e18.png)

**Comment by Dimosgr** [comment]
The corresponding file for polygon is the matic_helpers

**Comment by WombatFromHell** [comment]
I was thinking along the same lines before you responded, and it led me to a better, but not perfect, solution by using the contract of an LP pair (which is usually paired with a known token in that list you posted) that backs the unknown token. You can customize the existing contract loader in your project file. Obviously, this is a less than ideal solution as it adds to code duplication and has some limitations but it mostly works as long as one of the tokens in the pair is known.

I may look into a feature PR for this if I have free time so others could simply use a generic function and feed it an LP contract, MasterChef contract, and respective ABIs to get their token price for a token that has trouble finding price data. Anyway, my issue is mostly resolved so I'll just close this. I appreciate the response.
