### ISSUE TITLE
Elk Finance tracking for BSC + xDai

### ISSUE THREAD

**Issue by pyrosquid42** [vfat-tools/vfat-tools#1526]
xDai smart contracts & known liquidity pairs: https://docs.elk.finance/addresses#xdai-chain 
BSC smart contracts & known liquidity pairs: https://docs.elk.finance/addresses#binance-smart-chain-bsc

Thank you!

**Comment by jambestwick** [comment]
I'm trying to add it to all chains, but can not find the starking pools address

**Comment by Dimosgr** [comment]
Hi,I have managed to add elk on xdai chain. Nevertheless, I couldnt add it on bsc because of errors.
I cant find what the problem is because the contracts there are not verified.

![image](https://user-images.githubusercontent.com/36194185/130431825-c430b462-d02a-47eb-90a2-31c2e53dac92.png)

**Comment by Dimosgr** [comment]
Added elk on bsc too. Please wait for the next update.
