### ISSUE TITLE
Cannot get APR of ALCHEMIX?

### ISSUE THREAD

**Issue by Calen4ss** [vfat-tools/vfat-tools#1555]
@Dimosgr  
![tempsnip](https://user-images.githubusercontent.com/87116066/130940544-d8feed5c-1560-4336-9ce1-4c2451fca413.png)
Dear Dimosgr, notice that you did this file. Thanks a lot!
Seems it cannot cal the apr for this pool, want to know what happened.

**Comment by jambestwick** [comment]
@Dimosgr  good answer!
