### ISSUE TITLE
Request for Addition 

### ISSUE THREAD

**Issue by shirupromotions** [vfat-tools/vfat-tools#1598]
POLYGON NETWROK

MC Wiki: 0xe40065bdaab3b6a3e541929f897d4fbaaeafe175

POLY WIKI Token: 0xDaBbEc88827DC808cD1FA9336D186A0A2d469584
(PRE-SALE from Sept.2)

Website:
poly.FarmWiki.xyz

Network: Polygon

**Comment by Dimosgr** [comment]
Added please wait for the next update
