### ISSUE TITLE
Update MC on FARMWIKI POLYGON

### ISSUE THREAD

**Issue by shirupromotions** [vfat-tools/vfat-tools#1609]
Sorry guys i was just informed now of the changes in the MC of the farm

NEW MC:
0x3938C0fEcEF9a6d38050b424c4C6C2639E9d6A6F

PolyWiki PRESALE Token:
0xDaBbEc88827DC808cD1FA9336D186A0A2d469584
(PRESALE live)

PolyWiki Token:
0x5346D777E6433a9E64bc7b3C6315Fd145Ba4050C

Website:
poly.farmwiki.xyz

Network: Polygon

**Comment by shirupromotions** [comment]
Sir MC still not change the vfat link is not working.. :-(

**Comment by shirupromotions** [comment]
Initialized 0x35a273484b88822460ce5863ff1d16949e36fc1f

Reading smart contracts...

{
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": -32000,
    "message": "header not found"
  }
}
Oops something went wrong. Try refreshing the page.

**Comment by Dimosgr** [comment]
Yes please you have to wait for the next update
