### ISSUE TITLE
Request - demeter finance

### ISSUE THREAD

**Issue by deBatsniKov** [vfat-tools/vfat-tools#162]
Are you planning on adding demeterfinance.org

Thanks in advance for either a yes or a no!!
I love your website. Where is the donation address?

**Comment by bichuga** [comment]
Demeter rugged.

"for those of you who lost funds in the demeter rug, a tg group has been created for the victims:

https://t.me/dementerrecovery"

**Comment by deBatsniKov** [comment]
Yeah, ugly rug. Lost a lot of cash there...
