### ISSUE TITLE
AvaEagle

### ISSUE THREAD

**Issue by maname-secret** [vfat-tools/vfat-tools#1667]
EagleToken 0xa0818B489F85579d9C29d75b95B239418c9d8687
MasterChef 0x516CceEBCFD6f85e3d946bc60610c56841E82a8b
Timelock 0xBeb0849F908D154fe9f345Fd8530f386a8eaAF87

usdt 0xA70C60F57198AAC9892AfC467031D0c989bcB2A5
wavax 0x8509556D3d9D51b94B395E1087506632BbD1A99F

Website https://avaeagle.com/
TG https://t.me/avaeagle

**Comment by Dimosgr** [comment]
Added. Please wait for the next update to see it.
