### ISSUE TITLE
Basis Cash - BasV2 Pool Needs Update

### ISSUE THREAD

**Issue by bivalent** [vfat-tools/vfat-tools#169]
Currently the LP information uses the v1 BAS information which is out of date due to the v2 migration.

Some contract addresses to help:

**Boardroom v2**: https://etherscan.io/address/0xecf0dde35f6d895c065e7526348af1e79433e42a#code

**BasV2**: 0x106538cc16f938776c7c180186975bca23875287

**BasV2 LP Pair Token/Contract**: https://etherscan.io/token/0x3e78f2e7dade07ea685f8612f00477fd97162f1e

**Staking Pool for Basv2/Dai**: https://etherscan.io/address/0x3855c26d0621ceb21b5aaba0b8fe4ad76d658f7d#code

that uses as a wrapper/compatible upgrade/passthrough from before I think: https://etherscan.io/address/0x5859adb05988946b9d08dce2e12ae29af58120c0

**Comment by brent-riva** [comment]
Also, something to consider would be adding support for the onsen SLPs:

BAC/ETH: https://app.sushi.com/pair/0xfa8c3f98debf3d0a192e2edf9182352332def35c

BAC/BAB: 0x87bf6386f7611afa452c642c2835a305a692607d
