### ISSUE TITLE
can you check what's the problem with bloodyswap?

### ISSUE THREAD

**Issue by ghost** [vfat-tools/vfat-tools#1702]
bloodyswap keeps showing a JSON error I gotta refresh it multiple times to get it working and then when it goes it creates issues with staking, withdrawing and other things, and shows errored values of tvl too

WEBSITE: https://bloodyswap.finance

MASTERCHEF: 0xb0faE26e5C3282A5c919bBA32d168aAcD83B8194 (Polygon)

**Comment by Dimosgr** [comment]
Hi there. It works fine for me. Did you clear the browser storage? Maybe this fix your problem.
![image](https://user-images.githubusercontent.com/36194185/133212959-89ed515b-f880-4500-866a-9eef66018b17.png)

**Comment by vfat0** [comment]
This sounds like an RPC problem, try changing it on Metamask
