### ISSUE TITLE
Plenty on Tezos?

### ISSUE THREAD

**Issue by pikeas** [vfat-tools/vfat-tools#1724]
Would it be possible to add plentydefi.com on Tezos? Tezos is #31 by market cap, and Plenty has $35m TVL.

**Comment by vfat0** [comment]
at the minute we are only supporting EVM based chains, I assume Tezos is not?

**Comment by pikeas** [comment]
Ah, that makes sense. Tezos isn't EVM-compatible at this time. Appreciate the quick response!
