### ISSUE TITLE
Quickswap on Polygon - which file?

### ISSUE THREAD

**Issue by StayFoolisj** [vfat-tools/vfat-tools#1734]
Hey I'm expecting to find a file `matic_quick.js` in `src/static/js`. Which file is it that is responsible for Quickswap?

**Comment by vfat0** [comment]
that is the file yes, src/static/js/matic_quick.js

**Comment by StayFoolisj** [comment]
Sorry - I must have been blind. Was triple-checking before I posted, but was after a 10 hour code binge lol.
