### ISSUE TITLE
Moonlake on Moonriver err

### ISSUE THREAD

**Issue by moonlakemovr** [vfat-tools/vfat-tools#1785]
https://vfat.tools/moonriver/moonlake/

The page is stuck in 
"Reading smart contracts...

{}
Oops something went wrong. Try refreshing the page. "

Also, the moonlake is not listed on the moonriver page even though it's in the code

**Comment by vfat0** [comment]
kindly test any changes locally before submitting a pull request. we can have a look on Monday
