### ISSUE TITLE
Internal XML-RPC error on every site

### ISSUE THREAD

**Issue by ckv60** [vfat-tools/vfat-tools#1795]
Newly I'm getting this error on every page. Can't explore, why this happens so far. But it's not going on towards the next pools.
Thanks for review the code.
![grafik](https://user-images.githubusercontent.com/6459811/135121410-aa9d4d80-914a-4670-823b-1c31aefbabc8.png)

**Comment by vfat0** [comment]
is this on a specific network?

**Comment by ckv60** [comment]
I'm working with Fantom; Pools are Hyperjump, Zoo... it`s coming up on each pool

**Comment by Dimosgr** [comment]
Hello, it works for me fine. Maybe you have to change your rpc url. I am using this https://rpc.ftm.tools/
![Capture](https://user-images.githubusercontent.com/36194185/135215842-8f0fd778-f636-4422-ad15-c539ee947274.PNG)

**Comment by ckv60** [comment]
Hello,
thanks for support; I previously used rpcapi.fantom.network. => errors and switching account balances... irritating...  
  
Now using rpc.ftm.tools.... works great... awful and awesome to see... 
Thanks
