### ISSUE TITLE
ProcyonSwap the new center of the DeFi on #Fantom

### ISSUE THREAD

**Issue by secretemate** [vfat-tools/vfat-tools#1808]
ProcyonToken 0xc9cEE4fC03dA818b95D6abb9B0AA2bD0caFa6Fd0
MasterChef 0x7e9fFDF9C9fb466D02b7d7E915D2E8Bf223DE811
Timelock 0xC9ca89A862d615A3772Dd3211E6a6e91eD34AD4b

Website https://procyonswap.com/

**Comment by Dimosgr** [comment]
Added, Please wait for the next update in order to see it.
