### ISSUE TITLE
Sapphire DeFi Fantom

### ISSUE THREAD

**Issue by secretemate** [vfat-tools/vfat-tools#1835]
fSapphire 0xfa7d8c3CccC90c07c53feE45A7a333CEC40B441B
fSapphireMasterChef 0x5A3b5A572789B87755Fa7720A4Fae36e2e2D3b35
Timelock 0x87416d27f42a5aDa9A86e19B1CF5D2971fa1f648

https://sapphiredefi.com/

**Comment by vfat0** [comment]
please submit by pull request, we are no longer taking issues from your team due to unprofessional conduct
