### ISSUE TITLE
#request to add Beefy.Finance/Arbitrum

### ISSUE THREAD

**Issue by magsthegreat** [vfat-tools/vfat-tools#1852]
Thank you for everything that you do with the vfat suite of tools.  They're amazing.

Request to add the arbitrum instance of **Beefy.Finance**

**Links**:

https://app.beefy.finance/#/arbitrum 
https://github.com/beefyfinance/beefy-app

**Verified contracts:**  

MIM/USDC/USDT (Curve (MIM) / MIM) - 0xDa2307A45D298e855415675bF388e2bd64351D5b	
SPELL-ETH LP (Sushi / Sushi) - 0x149f3dDeB5FF9bE7342D07C35D6dA19Df3F790af	
TriCrypto (Curve / Curve) - 0xF26C10811D602e39580C9448944ddAe7b183fD95	
WBTC/renBTC (Curve / Curve) - 0x14d07853560436aEe38BE12DD66d944B07D5E59F	
MIM-ETH LP (Sushi / Sushi) - 0x80514CfB7cb438F1f997Ab62fFD1314c1a1c0f12	
USDC-ETH LP (Sushi / Sushi) - 0x07Db98358D58Ba9bE90cd0A18cd86AF807ac3B4E	
LINK-ETH LP (Sushi / Sushi) - 0xf785Ef43A082C85ABbe19CA888f91748AA604ac5	
USDC/USDT (Curve / Curve) - 0xEc7c0205a6f426c2Cb1667d783B5B4fD2f875434
USDT-ETH LP (Sushi / Sushi) - 0xE99c8A590c98c7Ae9FB3B7ecbC115D2eBD533B50	
WBTC-ETH LP (Sushi / Sushi) - 0xfcDD5a02C611ba6Fe2802f885281500EC95805d7	
SUSHI-ETH LP (Sushi / Sushi) - 0xBa5041B1c06e8c9cFb5dDB4b82BdC52E41EA5FC5

**Comment by Moonster-BSC** [comment]
A vault registry with a list of all of our vaults on chain is coming soon, which will help with this tremendously.
