### ISSUE TITLE
KLONDIKE PROTOCOL - Klon migration to V2 > OK - New asset kxUSD

### ISSUE THREAD

**Issue by Maoi420** [vfat-tools/vfat-tools#186]
Hi vfat tools team!

Klon is in the process of a 7 days migration, ending March 30th, pools and token will be worthless after that period.
Twitter: https://twitter.com/KlondikeFinance/status/1374714541850910723
Medium: https://klondikefinance.medium.com/on-the-way-to-v-2-ff078dc92dcc

Could you please update the data? 

The addresses are:

KLONX token: https://etherscan.io/token/0xbf15797BB5E47F6fB094A4abDB2cfC43F77179Ef
KLONX-WBTC Uniswap LP: https://etherscan.io/address/0x69cda6eda9986f7fca8a5dba06c819b535f4fc50
KBTC-WBTC V2 staking pool: https://etherscan.io/address/0x2b01d3e34259d40cf2ff3b34a28d7c80d6319cb0
KLONX-WBTC V2 staking pool: https://etherscan.io/address/0x185bdc02aafbecdc8dc574e8319228b586764415
KLONX Boardroom: https://etherscan.io/address/0xacbdb82f07b2653137d3a08a22637121422ae747
Uniswap Boardroom (to stake KLONX-WTBC UNI-V2 in boardroom): https://etherscan.io/address/0xd5b0ae8003b24ecf232d434a5f098ea821cf8ae3

Any more info needed, would be happy to answer on the TG/Discord,
Many thanks.

**Comment by Maoi420** [comment]
Hi,

Many thanks for the update for the migration, works like a charm as usual.

We have a new asset already launched on Klondike protocol: kxUSD
Twitter: https://twitter.com/KlondikeFinance/status/1380824828538720261

Would that be possible to add the new pool within Klondike vfat please?

kxUSD token: https://etherscan.io/token/0x43244c686a014c49d3d5b8c4b20b4e3fab0cbda7
kxUSD-DAI Uni pair: https://info.uniswap.org/pair/0x672c973155c46fc264c077a41218ddc397bb7532
kxUSD-DAI staking pool: https://etherscan.io/address/0xe301f632e573a3f8bd06fe623e4440560ab08692

A million thanks again!
Cheers

**Comment by Dimosgr** [comment]
Added, please check
