### ISSUE TITLE
Fools Guild representation request - LootSwap.Finance on Harmony

### ISSUE THREAD

**Issue by foolsguild** [vfat-tools/vfat-tools#1945]
All Time And Consideration Is Appreciated
I would like to submit for listing https://lootswap.finance/guilds/fool on the Harmony One Blockchain.
We wanted to see if it was possible to reuse the arb /bard/ troll guilds and change to this address: Master Looter -https://explorer.harmony.one/address/0x30cbeeb51fb8abe9cb34cc6780f133f0fecf6738?activeTab=7
FOOL Token: https://explorer.harmony.one/address/0x584705c40e7df1fcfc06cb0ad5223e0f5bc8e6e2?activeTab=7

**Comment by Dimosgr** [comment]
Hi there. There are 0 pools in the contract.
![image](https://user-images.githubusercontent.com/36194185/139646937-fefe0630-6213-4624-852b-957b8129184f.png)

**Comment by foolsguild** [comment]
yeah, I'm ahead of the ball, sorry about that. Will reply as soon as they are. I'm bad at this sorry lol

**Comment by Dimosgr** [comment]
Sure, take your time

**Comment by foolsguild** [comment]
> Sure, take your time

can you see them now?

**Comment by Dimosgr** [comment]
Yes added, please wait for the next update in order to see it.

**Comment by foolsguild** [comment]
> Yes added, please wait for the next update in order to see it.

thank you very much!
