### ISSUE TITLE
Emissions multiplier not reflected on VFAT APRs for Fool on Harmony

### ISSUE THREAD

**Issue by defigraal** [vfat-tools/vfat-tools#1949]
Hi,

The emissions multiplier is not being reflected on VFAT, for Fool on Harmony. It is displaying 16x lower APRs than the UI.

https://lootswap.finance/guilds/fool

At this point, the emission multiplier is 16x. On VFAT the APR for one of the pools is:

![image](https://user-images.githubusercontent.com/87538298/139928307-0b27f0d3-449c-486d-9723-9f5f9be3bb5a.png)

While the APR on the UI is:

![image](https://user-images.githubusercontent.com/87538298/139928395-c8dfc567-1929-4e44-9d58-2ee225daff80.png)

VFAT: 442.72%
UI: 7122.58%

442.72% * 16 = 7083.52% (there was a small delta between the two data fetches..)

The same applies to the other two pools.

How is the emissions multiplier reflected on VFAT ?

Thanks!

**Comment by defigraal** [comment]
A correction of the previous data. The emission rate is 16x, but distributed like:
14.4x to FOOL-ONE
0.8x to bscBUSD-BUSD
0.8x bscUSDC-USDC

Given this I can't keep considering it as the root cause for the divergence between the UI and VFAT.

Small simulation for bscBUSD pool, based on current data:

FOOL price $0.018
bscBUSD-BUSD liquidity $8762.22
UI APR 2599.87%

`calculated APR = 100*(((365*24*60*60)/2.0)*0.8*0.018)/8762.22 = 2591.34%`

VFAT APRs are much lower on all pools, even when the emission rate is lower than 1.

**Comment by defigraal** [comment]
I believe the root cause is in this commit:

https://github.com/vfat-tools/vfat-tools/commit/b3736d8e4fbebc24b93262568d0b659c7420d067#diff-14af102e0a1e8fb51d4bb59affcd481eb02c85ebf7764e5c743709642891702e

When it was "fixed" the multiplier was deleted.

**Comment by Dimosgr** [comment]
Ok fixed, please wait for the update. The problem was that the block number was a big int and it has to be multiplied by 1 in order to become a number.

![image](https://user-images.githubusercontent.com/36194185/140029816-e3d22ecf-34c3-430a-93c3-cc66d35805f8.png)
