### ISSUE TITLE
Error Reading Smart Contracts - FATExDAO | Harmony

### ISSUE THREAD

**Issue by Ciantera-Rose** [vfat-tools/vfat-tools#1955]
Hi there, reaching out to find a resolution for the FATExDAO vfat tools error (Harmony Blockchain). It's been down for several days for our community. We were doing contract / DEX upgrades on our end and waited to see if that's what was causing the issue. Please let me know when someone on your end can look into this issue for us? I have attached screenshots of the errors as well. 

Thanks!

**Screenshot Error before DEX Upgrades:**
<img width="1221" alt="fatexdao_vfat" src="https://user-images.githubusercontent.com/71797785/140080459-555ce59e-8155-4df7-8d3f-2e5c82196123.png">

**Screenshot Error after DEX Upgrades:**
<img width="1182" alt="Vfat-Error" src="https://user-images.githubusercontent.com/71797785/140080192-e414391f-e99b-4326-b44d-11bb5c897b5c.png">

**Comment by vfat0** [comment]
Hello, yes there is a problem with your recent update. We can help but you have to verify the contracts first, otherwise we don't know what we're looking at. e.g. https://explorer.harmony.one/address/0x8ecafea764237d239d7fcc3a90f1cf0c95cc9a1f?activeTab=7

**Comment by Ciantera-Rose** [comment]
@coreycaplan3 Can you take a look at this and verify and publish smart contract(s) involved with vfat stats?

**Comment by Ciantera-Rose** [comment]
Hello again @vfat0 ... Our incredible dev verified the contracts and submitted a pull request to merge the improved and updated FATEx implementation. Thanks!

**Comment by Dimosgr** [comment]
Ok the PR has updated

![image](https://user-images.githubusercontent.com/36194185/140918290-24859b16-7d4f-4bc0-a266-09e7420940b3.png)
