### ISSUE TITLE
Local installation problems

### ISSUE THREAD

**Issue by ckv60** [vfat-tools/vfat-tools#1960]
Hello vfat;
I wanted to install tools locally on a new node.js install.  But getting errors, which I can't understand and resolve.
So help would be very nice.
Error during install is:

C:\Program Files\nodejs\vfat-tools-master>npm install
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kuepers\AppData\Local\npm-cache\_logs\2021-11-04T15_13_16_638Z-debug.log

C:\Program Files\nodejs\vfat-tools-master>npm run dev

> yieldfarming.info@1.0.0 dev
> npm run setup-for-dev && npm-run-all --parallel start watch:*

> yieldfarming.info@1.0.0 setup-for-dev
> NODE_ENV=development npm-run-all --sequential rmprod copy-to-dist build:html

Der Befehl "NODE_ENV" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

*********
Here ends my understanding... sorry to say that. For information I attach also the complete install.log. 
Hopefully you can say, how to solve... 
Thanks in advance.

[2021-11-04T15_13_16_638Z-debug.log](https://github.com/vfat-tools/vfat-tools/files/7476003/2021-11-04T15_13_16_638Z-debug.log)

**Comment by vfat0** [comment]
hello, looks like you don't have git installed for the first error. for the second error it is because the command is made for linux. my usual recommendation for windows users is to use WSL

**Comment by ckv60** [comment]
thanks; i will check with my collegue

**Comment by ckv60** [comment]
my collegue has done changes for local windows install; now everything works fine. thanks for support.
