### ISSUE TITLE
Bootyswap

### ISSUE THREAD

**Issue by A144580** [vfat-tools/vfat-tools#1980]
https://app.bootyswap.finance/

masterchef
0xf2a26B610752b96B9B9aD813010300e8EbfEF13e

token 
0xFA17625B24854aac5B029Fb8140Af111e980476C

masterchef
https://bscscan.com/address/0xf2a26B610752b96B9B9aD813010300e8EbfEF13e

https://bscscan.com/address/0xFA17625B24854aac5B029Fb8140Af111e980476C

**Comment by Dimosgr** [comment]
Added please wait for the next update
