### ISSUE TITLE
#Request to add https://monsterfinance.app/ running over Fantom opera

### ISSUE THREAD

**Issue by mnstrfarm** [vfat-tools/vfat-tools#2008]
MNSTR Token - https://ftmscan.com/address/0x1bc65518565136518ba1212EF5045C6317E5d993

MNSTR Masterchef - https://ftmscan.com/address/0x1FC8E34DA45dBC6cc95CdE2Ee9C943809702951f

Thankyou
Regards 
Monster Farm

**Comment by Dimosgr** [comment]
Added, Please wait for the next update in order to see it.
