### ISSUE TITLE
Showing incorrect data for DeFi Kingdoms -> JEWEL/USDC pool

### ISSUE THREAD

**Issue by federico-r-figueredo** [vfat-tools/vfat-tools#2043]
Greetings,

While mi JEWEL/ONE staking is fetching data correctly...
![imagen](https://user-images.githubusercontent.com/49570839/143381335-121df28d-478b-419c-93ba-66de754d8497.png)

That's not the case for JEWEL/USDC...
![imagen](https://user-images.githubusercontent.com/49570839/143381487-64e79d57-6b6a-4be2-8ae4-9f8ef41aea42.png)

As we can verify on DK's UI...
![imagen](https://user-images.githubusercontent.com/49570839/143381621-9c7035f2-b574-46f7-bbdc-31b0ecd4206c.png)

Nevertheless, at the bottom it adds both pools asset values correctly...
![imagen](https://user-images.githubusercontent.com/49570839/143381690-254cf1db-03e1-4ab4-abb7-bdc55e6800be.png)

IDK if this is an intrinsinc problem within this project. It could reside on the third party API where data is fetched from.

Anyway if dev/s 're busy I can run this app in local env. this weekend and help debugging this issue.

Best Regards.

**Comment by Dimosgr** [comment]
Added 6 more decimals to LPs. Please check

**Comment by federico-r-figueredo** [comment]
Damn I'm dumb. I missed the decimals 😅
Thx. Working like a charm now.
