### ISSUE TITLE
#request to add Tethys Finance on Metis 

### ISSUE THREAD

**Issue by meyers4549** [vfat-tools/vfat-tools#2115]
Token: TETHYS - https://andromeda-explorer.metis.io/address/0x69fdb77064ec5c84FA2F21072973eB28441F43F3/contracts
MasterChef: https://andromeda-explorer.metis.io/address/0x54A8fB8c634dED694D270b78Cb931cA6bF241E21/contracts

Tradeable on https://tethys.finance in TETHYS-METIS pair

Factory: https://andromeda-explorer.metis.io/address/0x2CdFB20205701FF01689461610C9F321D1d00F80/contracts
LP token: https://andromeda-explorer.metis.io/address/0xc9b290ff37fa53272e9d71a0b13a444010af4497/contracts

**Comment by Dimosgr** [comment]
Hello. Added please wait for the next update in order to see it
