### ISSUE TITLE
for Addition

### ISSUE THREAD

**Issue by shirupromotions** [vfat-tools/vfat-tools#2144]
CEN 0xe4587C2c58eaD7f927B4B58a53Aa2724f238dFEC
MC 0x6a7330ac91A59B84423c374c32374dfb6839Aa7D
https://cen.centaurus.network/
VELAS

**Comment by Dimosgr** [comment]
Hi. There is an error message in the read-contract section in explorer page and I cant see the functions.

https://evmexplorer.velas.com/address/0x6a7330ac91A59B84423c374c32374dfb6839Aa7D/read-contract

**Comment by shirupromotions** [comment]
Noted I'll ask dev about this
