### ISSUE TITLE
List $PLOT staking, Stake PLOT earn MATIC

### ISSUE THREAD

**Issue by guptashutosh** [vfat-tools/vfat-tools#2151]
Hi guys, we launched our staking program a few days ago, would be great if it gets listed on the website. Huge fan btw!

Details - https://medium.com/plotx/single-sided-plot-staking-is-here-stake-plot-earn-upto-100k-every-month-in-matic-bplot-bf7ade3888f0

Page - https://plotx.io/stake/PLOT/0x04b2aefb8e8d0f8180265c3b73b5ff012af3b633 

Reward tokens - MATIC & bPLOT, tiered rewards based on $PLOT staked

**Comment by Dimosgr** [comment]
Hello there. Could you send me please the staking contract address in order to see how complex is the code and try to added it? Thanks in advance.

**Comment by guptashutosh** [comment]
Contract address - 0x04b2aefb8e8d0f8180265c3b73b5ff012af3b633

**Comment by Dimosgr** [comment]
It needs verified https://polygonscan.com/address/0x04b2aefb8e8d0f8180265c3b73b5ff012af3b633#code

![image](https://user-images.githubusercontent.com/36194185/150385858-f85ac885-d3fc-4998-ae79-876c100807f1.png)

**Comment by guptashutosh** [comment]
It's verified now
