### ISSUE TITLE
New addition AgeFantom $AOD (Fantom

### ISSUE THREAD

**Issue by JadeBaka** [vfat-tools/vfat-tools#2152]
Hey, can you guys please add AgeFantom from the Fantom network?

Masterchef: https://ftmscan.com/address/0x91121c30d9c5699750d879f529039fd4d0639f80
Token: https://ftmscan.com/address/0x632819c470cf8c1b4b09ca12d5d3e0c2d19c987d
Website: https://dark.knightswap.financial/

Cheers , TY!

**Comment by Dimosgr** [comment]
Hi there. Ok added on knightswap and represend it as updated with * . Please wait for the next updated in order to see it.

**Comment by JadeBaka** [comment]
Oh no my mistake! Our website is actually https://agefantom.com/#/ 

Can you please undo the changes that are occurred on knightswap?

Apologies for my mistake
