### ISSUE TITLE
Please Add TheAnimal.Farm to BSC 

### ISSUE THREAD

**Issue by cryptokinglegend** [vfat-tools/vfat-tools#2191]
Please add theanimal.farm ... They have various pools and farms, and a PIG PEN that yields BUSD.

**Comment by Dimosgr** [comment]
Hi, the project is already on the list.
![image](https://user-images.githubusercontent.com/36194185/152671404-258df049-22cc-4b87-bc9d-5ba791ca6819.png)

**Comment by cryptokinglegend** [comment]
Thank you!
