### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by Avaritia06** [vfat-tools/vfat-tools#224]
Hi Vfat, 
Would like to request if possible to add favorites in the Vfat Tools, this way it is much easier to navigate farms attach to the wallet addrees, or just add favorites. thank you

**Comment by Avaritia06** [comment]
or just an additional check box beside the pool provider, and another tab called favorites which lists the selected checked box. thank you

**Comment by eugenioclrc** [comment]
Hey Vfat, is there anyway of knowing the withdrawal or deposit fees?

**Comment by jambestwick** [comment]
ok ，its a good idea，but its need user managment system, and login logout
