### ISSUE TITLE
Can not run the project on my PC (Windows 10)

### ISSUE THREAD

**Issue by thunderstroke325** [vfat-tools/vfat-tools#2251]
Hi, there. Thanks for sharing this project.
I tried to runt his project locally on my PC (Windows 10), but I got failed.
Once clone the project, I installed node modules with this command "npm install ". 
After installed all modules, I try this command "npm run dev". but it shows some issue and failed.

This is what I got on my side.

> yieldfarming.info@1.0.0 dev D:\Project\02.Proceeding\vfat-tools
> npm run setup-for-dev && npm-run-all --parallel start watch:*

> yieldfarming.info@1.0.0 setup-for-dev D:\Project\02.Proceeding\vfat-tools
> NODE_ENV=development npm-run-all --sequential rmprod copy-to-dist build:html

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yieldfarming.info@1.0.0 setup-for-dev: `NODE_ENV=development npm-run-all --sequential rmprod copy-to-dist build:html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yieldfarming.info@1.0.0 setup-for-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ghost\AppData\Roaming\npm-cache\_logs\2022-03-07T03_42_36_705Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! yieldfarming.info@1.0.0 dev: `npm run setup-for-dev && npm-run-all --parallel start watch:*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yieldfarming.info@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ghost\AppData\Roaming\npm-cache\_logs\2022-03-07T03_42_36_776Z-debug.log

I am not sure why this happen and how to fix this one.

**Comment by thunderstroke325** [comment]
I just found how to solve this issue.
It only occurs on the Windows. I fixed this issue by update package.json file.

This is original configurations.

  "scripts": {
    "start": "browser-sync start -s 'dist' -f 'dist' --no-open --no-notify --reload-debounce 50",
    "setup-for-dev": "NODE_ENV=development npm-run-all --sequential rmprod copy-to-dist build:html",
    "dev": "npm run setup-for-dev && npm-run-all --parallel start watch:*",
    "build": "NODE_ENV=production npm-run-all --sequential rmprod copy-to-dist minify:js minify:css prepend-banner hash-filenames minify:html",
    "build:html": "NODE_ENV=development babel-node build-tools/ejs-to-html.mjs",
    "build:js": "NODE_ENV=development npx webpack -d",
    "build:css": "NODE_ENV=development npm run sass && npm run autoprefixer",
    "watch:html": "NODE_ENV=development babel-node build-tools/ejs-to-html.mjs --watch",
    "watch:js": "NODE_ENV=development npx webpack -w -d --display minimal",
    "watch:css": "NODE_ENV=development npm run sass && node-sass -w -r src/css -o dist/css --source-map true",
    "minify:html": "NODE_ENV=production npm run build:html && babel-node build-tools/minify-html.js",
    "minify:js": "NODE_ENV=production npx webpack -p",
    "minify:css": "NODE_ENV=production npm run build:css && babel-node build-tools/minify-css.js",
    "sass": "node-sass src/css -o dist/css --source-map-embed true",
    "autoprefixer": "postcss dist/css/**/*.css --use autoprefixer -r",
    "copy-to-dist": "babel-node build-tools/copy-to-dist.mjs",
    "hash-filenames": "babel-node build-tools/hash-filenames.js",
    "prepend-banner": "babel-node build-tools/prepend-banner.js",
    "rmprod": "rimraf filename-map.json && rimraf dist",
    "prettier": "prettier --write 'src/**/*.{js,css,scss,json,html}'",
    "deploy": "gh-pages -d dist"
  },

I update this configuration like this.
  "scripts": {
    "start": "browser-sync start -s 'dist' -f 'dist' --no-open --no-notify --reload-debounce 50",
    "setup-for-dev": "set NODE_ENV=development npm-run-all --sequential rmprod copy-to-dist build:html",
    "dev": "npm run setup-for-dev && npm-run-all --parallel start watch:*",
    "build": "NODE_ENV=production npm-run-all --sequential rmprod copy-to-dist minify:js minify:css prepend-banner hash-filenames minify:html",
    "build:html": "set NODE_ENV=development babel-node build-tools/ejs-to-html.mjs",
    "build:js": "set NODE_ENV=development npx webpack -d",
    "build:css": "set NODE_ENV=development npm run sass && npm run autoprefixer",
    "watch:html": "set NODE_ENV=development babel-node build-tools/ejs-to-html.mjs --watch",
    "watch:js": "set NODE_ENV=development npx webpack -w -d --display minimal",
    "watch:css": "set NODE_ENV=development npm run sass && node-sass -w -r src/css -o dist/css --source-map true",
    "minify:html": "NODE_ENV=production npm run build:html && babel-node build-tools/minify-html.js",
    "minify:js": "NODE_ENV=production npx webpack -p",
    "minify:css": "NODE_ENV=production npm run build:css && babel-node build-tools/minify-css.js",
    "sass": "node-sass src/css -o dist/css --source-map-embed true",
    "autoprefixer": "postcss dist/css/**/*.css --use autoprefixer -r",
    "copy-to-dist": "babel-node build-tools/copy-to-dist.mjs",
    "hash-filenames": "babel-node build-tools/hash-filenames.js",
    "prepend-banner": "babel-node build-tools/prepend-banner.js",
    "rmprod": "rimraf filename-map.json && rimraf dist",
    "prettier": "prettier --write 'src/**/*.{js,css,scss,json,html}'",
    "deploy": "gh-pages -d dist"
  },

Now above issue "'NODE_ENV' is not recognized as an internal or external command" doesn't appear anymore.

**Comment by jambestwick** [comment]
@thunderstroke325 
use "cross-env" pre "NODE_ENV" instead  "set"
![image](https://user-images.githubusercontent.com/18340126/157158884-dacacb46-e738-4730-a794-72dfa02c3150.png)

**Comment by thunderstroke325** [comment]
Thanks for your advice
