### ISSUE TITLE
Please Update zombfinance.com Farm

### ISSUE THREAD

**Issue by dukemc1** [vfat-tools/vfat-tools#2267]
New farm added 

ZOMB-USDC
Contract: 0x724783fde5c8d0caf60f780f4a45430da4d72544

_pid 3

**Comment by dukemc1** [comment]
The Usdc-Zomb pool do not show up on the Webinterface?

**Comment by Dimosgr** [comment]
It will be shown up with the next update of site. I think that is scheduled for today.

**Comment by dukemc1** [comment]
> It will be shown up with the next update of site. I think that is scheduled for today.

Oh thank you - thought update is daily :)
