### ISSUE TITLE
Please Add New Fantom Farm ftm.piggyfinance.io

### ISSUE THREAD

**Issue by dukemc1** [vfat-tools/vfat-tools#2281]
Please add piggyfinance fantom.

Contracts

TPiggy- 0x0d3d5BF98D7B9961C602fbfB8032c7BDC6a0C386

PShare- 0xf6036DD216B6B97482510CB647c5D1fEB83cE910

TPBond- 0xc60dF34E0e3A2806aE41c47FeB03F467a3eaC2ad

Masonry- 
0xBF7DA01f806F9E01C62C887003b8C9761B169B76

TPiggyGenesisPool- 0x578B2a5dd65c2450aA9C5e03f95f2e1CbAe7661F

PShareRewardPool- 0xD742992bc78852E1c5cfbC70eA3c72689Fa72304 Reward Pools from _pid 0 and 1 

TPIGGY-TSHARE LP- 0x5743D7751a525c5D74Be9227829800c8542f97FF

PSHARE-FTM LP- 0xBeFB04a37E0b53AaebA58aCdFbeF6437312Dbd60

**Comment by Dimosgr** [comment]
Hello there. I cant read the contract from the mansory
https://ftmscan.com/address/0xBF7DA01f806F9E01C62C887003b8C9761B169B76#code

**Comment by dukemc1** [comment]
> Hello there. I cant read the contract from the mansory https://ftmscan.com/address/0xBF7DA01f806F9E01C62C887003b8C9761B169B76#code

It seems the Mansory is not live yet the farm rewards start in 12 Hours

**Comment by Dimosgr** [comment]
Oh ok. I will just push the farming for now

**Comment by dukemc1** [comment]
Thank you :)
