### ISSUE TITLE
Please add ftm.chargedefi.fi in fantom

### ISSUE THREAD

**Issue by dukemc1** [vfat-tools/vfat-tools#2298]
Please add ftm.chargedefi.fi they are also on BSC and on vfat:

Static:  0x27182C8b647fd83603bB442C0E450DE7445ccfB8

Charge: 0xe74621A75C6ADa86148b62Eef0894E05444EAE69

Static-USDC LP: 0x34011465A924C554220E768dcB27d59124Ce3Fa6

Charge-USDC LP: 0x5d2e8a24028F5749eC58b053B38D5aaFa57c2691

2 Farms active boardroom starts in 5 days.

**Comment by Dimosgr** [comment]
Hi. I have added it but the site has not been updated yet. You have to wait until the next update. I dont know exactly when maybe on Monday.

**Comment by dukemc1** [comment]
Hi it show on the site but throws this error :

Oops something went wrong. Try refreshing the page.

**Comment by Dimosgr** [comment]
Hi mate. It was a general problem. works now 
![image](https://user-images.githubusercontent.com/36194185/163941977-91484313-bb1a-4b22-b64c-3d3cda7a2919.png)
