### ISSUE TITLE
Can you please add Boardroom for ftm.chargedefi.fi in fantom

### ISSUE THREAD

**Issue by dukemc1** [vfat-tools/vfat-tools#2302]
Single Charge Boardroom:

https://ftmscan.com/address/0x7e8ecc1671e01788ec2fe9090c71e54cb6ad0110#code

Static-USDC Boardroom:

https://ftmscan.com/address/0xf6dfee99a7f2ce4431b641d1154b6c1b192a839c#code

**Comment by dukemc1** [comment]
It would be nice if the APR gets displayed and the daily and weekly earnings from the boardroom, they have done it here:

https://vfat.tools/bsc/charge/ 

i don´t know how much it takes to adapt this for FTM? if it is too much i understand that this could not be implemented.

**Comment by Dimosgr** [comment]
sure. I have just pushed it
