### ISSUE TITLE
Request to Add Pandoraswap

### ISSUE THREAD

**Issue by PandoraswapFinance** [vfat-tools/vfat-tools#2307]
Pandora Token:-   0x8ea356004327E598729b4CE590eDC90428Dc6A89
MasterPandora:-  0x894d03D77b42bBeC83CEe221596ba17a83b995eC
Referral :- 0x1313bF6D51026CDaD577ac09D19A498aE044d37f

Website:-https://pandoraswapxyz.org/

Network:- Astar network

**Comment by Dimosgr** [comment]
Hi just added. Please wait for the next update of the site in order to see it.
