### ISSUE TITLE
Request to add DEI finance on Fantom

### ISSUE THREAD

**Issue by bennnrenshaw** [vfat-tools/vfat-tools#2333]
Please let me know if you need anymore info! 

https://app.dei.finance

DEI / bDEI 
https://ftmscan.com/token/0xdce9ec1eb454829b6fe0f54f504fef3c3c0642fc?a=0xfb7405075f2dD0A2aacA6cA2D87D56e09577D6eF

**Comment by bennnrenshaw** [comment]
thanks @Dimosgr

**Comment by Dimosgr** [comment]
No problem :) will be showed up by the next update of the site.

**Comment by bennnrenshaw** [comment]
I see it on the website but the APR is NaN, will it become visible or not? Sorry, not sure if DEI has different contract !

**Comment by Dimosgr** [comment]
Yes and because we are missing the DEUS price which is the reward token. I couldn't find it in coingecko or in an LP token.

**Comment by bennnrenshaw** [comment]
Oh Sure, here is :
DEUS 
https://www.coingecko.com/en/coins/deus-finance

and DEI 
https://www.coingecko.com/en/coins/dei-token

**Comment by Dimosgr** [comment]
Ok for DEUS but now there is no price for DEI / bDEI token
https://ftmscan.com/address/0xDce9EC1eB454829B6fe0f54F504FEF3c3C0642Fc#readContract

**Comment by bennnrenshaw** [comment]
okay i will ask in the discord and update this ticket. Thanks a lot for your help!!! Really appreciate it

**Comment by bennnrenshaw** [comment]
can you use this for the bDEI price? 

https://ftmscan.com/address/0x9cac3ce5d8327aa5af54b1b4e99785f991885bf3#readProxyContract

**Comment by Dimosgr** [comment]
dont understand the calculations. Is this the correct price for bDEI - DEI?
![image](https://user-images.githubusercontent.com/36194185/173362912-23b7a857-832f-4384-8eb1-7d66fc0a14a6.png)

**Comment by Dimosgr** [comment]
thanks got it :)
![image](https://user-images.githubusercontent.com/36194185/173374976-43b1bd8e-9401-4014-913b-5cf744a4dd20.png)
