### ISSUE TITLE
Add vAMM-USDC/agEUR to Velodrome Optimism

### ISSUE THREAD

**Issue by bennnrenshaw** [vfat-tools/vfat-tools#2342]
Please can you add the LP to the Velodrome list? 

Contract : https://optimistic.etherscan.io/token/0x7866c6072b09539fc0fde82963846b80203d7beb?a=0xfb7405075f2dd0a2aaca6ca2d87d56e09577d6ef

Website : https://app.velodrome.finance/

On vfat : https://vfat.tools/optimism/velodrome/

**Comment by Dimosgr** [comment]
Hello, has been already listed
![image](https://user-images.githubusercontent.com/36194185/182081478-ad17ce38-3fbf-418f-991a-cfb9902d4648.png)
