### ISSUE TITLE
Please add Cowaii cash on Dogechain

### ISSUE THREAD

**Issue by surfacing8671** [vfat-tools/vfat-tools#2353]
Contracts

Cowaii = 0xB483CbF402eF2B07060544e4aA4c5690fea32B12

Milk = 0xc90163b8d53F319AbE68dd1d8ecC025c72eB3f04

Curd = 0x8a18Fc9C600780476ebda2742d7d53Fb5ac0EC21

Cowaii - wdoge lp = 0xe0d79F5Bc8e86E9123cA14937ca791128D013130

Milk - wdoge lp = 0x77A86d9c3A7689cD6577a6FC433a19f7c1686198

CowaiiGenesisRewardPool = 0x8E80AE7F27457896bc285c2b92F8463E88446768

Oracle = 0x5543FDf8126A50c5596FEbAB8BA80e1bc4e68F78

MilkRewardPool = 0xb015d1D4F846D44A699F5648071496D1eC99C4C5

Treasury: 0x994fede98Fa76C6858ce11D87A7f36dbAA17802d

**Comment by Dimosgr** [comment]
Hello, added please check
https://vfat.tools/doge/cowaii/
