### ISSUE TITLE
Please add HandleFi LPs on Arbitrum

### ISSUE THREAD

**Issue by bennnrenshaw** [vfat-tools/vfat-tools#2368]
Please can you add handle.fi LP and keepers (if possible) 

fxUSD / 2CRV Contract : https://arbiscan.io/token/0xd0dd5d76cf0fc06dabc48632735566dca241a35e

fxUSD / 2CRV Staking Contract : https://arbiscan.io/address/0x68f03c9db2611c79aaa21b6dfcdf6bac0cd191f6

FXkeeper Contract : https://arbiscan.io/address/0xc55204d4699dcce457dbf63d4b0074e6e1fa4412 

Website : https://app.handle.fi/

Let me know if you need anything else!

**Comment by Dimosgr** [comment]
Hi, im trying to find these staking contracts but i cant.
![image](https://user-images.githubusercontent.com/36194185/200110503-bb15f5b6-79f4-4ba1-814d-7ad4f9aafd0f.png)

In addition, I cant see the code of this contract for example
fxUSD / 2CRV Staking Contract : https://arbiscan.io/address/0x68f03c9db2611c79aaa21b6dfcdf6bac0cd191f6
![image](https://user-images.githubusercontent.com/36194185/200110716-5374a8f1-2ab6-4498-9ab0-b92d335dabb8.png)

**Comment by Dimosgr** [comment]
or these
![image](https://user-images.githubusercontent.com/36194185/200110884-c398aa3f-3611-4bef-b972-3c410e37f0bc.png)

**Comment by Dimosgr** [comment]
Closed because of inactivation
