### ISSUE TITLE
Please add BoC Protocol Link.

### ISSUE THREAD

**Issue by ZhangBrain** [vfat-tools/vfat-tools#2372]
Website:https://bankofchain.io/

USD(USDT/USDC/DAI) Vault Contract: 0x30D120f80D60E7b58CA9fFaf1aaB1815f000B7c3
ETH(ETH/WETH) Vault Contract: 0x8f0Cb368C63fbEDF7a90E43fE50F7eb8B9411746

**Comment by Dimosgr** [comment]
Hi, actually there are a lot of strategy contracts inside vaults contracts and this makes it difficult. In addition, the code in the strategy contracts cant be read it.
Furthermore, I couldnt find functions for users details. staked, rewards etc...

**Comment by ZhangBrain** [comment]
> Hi, actually there are a lot of strategy contracts inside vaults contracts and this makes it difficult. In addition, the code in the strategy contracts cant be read it. Furthermore, I couldnt find functions for users details. staked, rewards etc...

Our Protocol does not have our own governance token rewards for the time being, only rewards from 3-rd Protocols, and we will automatically sell mines and reinvest. Are we eligible for listing, and if not, what do we need to do?

**Comment by Dimosgr** [comment]
Yes you are eligible, but you have to do it by your self by creating a pull request.

**Comment by ZhangBrain** [comment]
> Yes you are eligible, but you have to do it by your self by creating a pull request.

That's great! Thanks!
