### ISSUE TITLE
Add MasterChef for DarwinSwap (by Darwin Protocol)

### ISSUE THREAD

**Issue by ghost** [vfat-tools/vfat-tools#2402]
Project URL: https://darwinswap.com/farming
MasterChef: https://arbiscan.io/address/0xabdf1bdbfc6c4e52420a22f05c7b36193e3722ce#code

**Comment by Dimosgr** [comment]
Hello. its still an empty contract thus i cant read the data yet

![image](https://github.com/vfat-tools/vfat-tools/assets/36194185/556655a5-bc43-470c-a05d-500fae0b1ab6)

**Comment by SmartGambleDev** [comment]
Oh pardon. I thought you were able to do the logic without pools. Yea it's still empty, we will add pools between tomorrow and the day after. Can I add a comment to this issue when we do? Or should I open another one?

**Comment by Dimosgr** [comment]
Hey 🙂 just comment here when it's ready. That's why I haven't closed it yet!

**Comment by Dimosgr** [comment]
I have just checked your contract and seen that there is a pool to stake. Nevertheless, your site seems doesnt work https://darwinswap.com/farming

**Comment by Dimosgr** [comment]
closed because of inactivation
