### ISSUE TITLE
Local running website displays an error

### ISSUE THREAD

**Issue by DettoFinance** [vfat-tools/vfat-tools#2408]
Hi, there. Thanks for sharing this project.
I tried to run this project locally on my PC (Windows 10),but when I access the webpage, an error is displayed.
This is what I got on my side.
![a](https://github.com/vfat-tools/vfat-tools/assets/147574293/e5ac190e-2fc8-4f87-bda3-fd859cf3513c)

http://localhost:3000
![b](https://github.com/vfat-tools/vfat-tools/assets/147574293/589764c9-8d6e-45e2-aa31-d0de5a3f7213)

**Comment by vfat0** [comment]
Can you show a screenshot of what it shows at localhost:3000?

**Comment by DettoFinance** [comment]
This is what i got 
![b](https://github.com/vfat-tools/vfat-tools/assets/147574293/62423c13-a21e-4660-95cd-53d1ba5ee17d)

**Comment by vfat0** [comment]
Try disabling your proxy / vpn if you are using one

**Comment by DettoFinance** [comment]
I am not using a proxy / vpn

**Comment by vfat0** [comment]
Your external IP is 26.26.26.1? Sorry I can't think of any other possible issue here.

**Comment by DettoFinance** [comment]
It could be a network issue, thank you
