### ISSUE TITLE
How to run this app?

### ISSUE THREAD

**Issue by jl2035** [vfat-tools/vfat-tools#343]
The readme is very brief. Instructions on what is required and how to run would be very nice.

**Comment by vfat-tools** [comment]
Good point yes!

**Comment by jl2035** [comment]
I've tried "npm install" and "npm start" and it works, but now I don't understand how to navigate to the app. Port 3000 says: "Cannot GET /". I'm probably missing something, right?

**Comment by vfat-tools** [comment]
For `npm start` to work you have to `npm build` first
