### ISSUE TITLE
badger.finance LP values need more decimal places

### ISSUE THREAD

**Issue by fafrd** [vfat-tools/vfat-tools#39]
Badger.finance allows users to stake LP tokens from Uniswap and Sushiswap. Unless you have hundreds of BTC staked, the values for the LP tokens are very small- for example, 0.0000000001 sushiswap LP token represents 0.5 wbtc + 0.5 digg.

For these tokens, the interface should display more than 8 decimal places. The [values in src/static/js/badger.js](https://github.com/vfat-tools/vfat-tools/blob/1fcc418640a353ad5e0b32e1c6ab14327da405a4/src/static/js/badger.js#L222-L225) should probably be bumped up to the full 18 decimal places.

**Comment by vfat-tools** [comment]
Good point yes I've amended, thank you!
