### ISSUE TITLE
Reduce call numbers by implementing multicall 

### ISSUE THREAD

**Issue by penandlim** [vfat-tools/vfat-tools#394]
https://github.com/makerdao/multicall

Should be able to deploy this contract on any EVM compatible chains then generalize the js files to work with any chain. At the least, this should reduce to 1 call to fetch the list of the pools and 1 call per pool info (or 1 call for all the pools depending on implementation)

**Comment by penandlim** [comment]
https://github.com/vfat-tools/vfat-tools/blob/0998e89ceeeb6596ea22490283c0e502ffdcca26/src/static/js/matic_helpers.js#L138

One instance where you would implement multicall is this function. Instead of awaiting multiple read calls, you can aggregate all read calls into one call to the multicall contract. This will help users not get rate limited and increase the load time significantly for some of the longer lists.

**Comment by vfat-tools** [comment]
You're absolutely right, I do use ethcall for ETH but I haven't gotten round to deploying it for the other chains

**Comment by penandlim** [comment]
Keep up the good work ser!

**Comment by jambestwick** [comment]
good
