### ISSUE TITLE
On Matic, Uniswap is called and not Quickswap

### ISSUE THREAD

**Issue by joris2020** [vfat-tools/vfat-tools#397]
On the Matic pages, when you click on the buttons: [+] [-] [<=>] above a pool, they all calls Uniswap and not Quickswap. 

These are super useful so you don't have to hunt for token contract addresses, pools etc.

**Comment by About7Sharks** [comment]
https://github.com/vfat-tools/vfat-tools/blob/f981f31649a22921220368012c9762da33e35a65/src/static/js/ethers_helper.js

**Comment by About7Sharks** [comment]
I tried to pull the code and push a new branch for a pr but don't have proper access to the repo. 
Adding ```chain=='matic'``` to [file](https://github.com/vfat-tools/vfat-tools/blob/f981f31649a22921220368012c9762da33e35a65/src/static/js/ethers_helper.js) will work 

```
        pool.symbol.includes("Cake") ? [
          `https://exchange.pancakeswap.finance/#/add/${t0address}/${t1address}`, 
          `https://exchange.pancakeswap.finance/#/remove/${t0address}/${t1address}`, 
          `https://exchange.pancakeswap.finance/#/swap?inputCurrency=${t0address}&outputCurrency=${t1address}` 
        ] :
        chain=='matic'? [
          `https://quickswap.exchange/#/add/${t0address}/${t1address}`,
          `https://quickswap.exchange/#/remove/${t0address}/${t1address}`,
          `https://quickswap.exchange/#/swap?inputCurrency=${t0address}&outputCurrency=${t1address}` 
        ] :
        pool.name.includes("Value LP") ? [
          `https://bsc.valuedefi.io/#/add/${t0address}/${t1address}`, 
          `https://bsc.valuedefi.io/#/remove/${t0address}/${t1address}`, 
          `https://bsc.valuedefi.io/#/swap?inputCurrency=${t0address}&outputCurrency=${t1address}` 
        ] :

```

**Comment by vfat-tools** [comment]
Thank you for this yes, the method to propose changes to the repo is a pull request:
-Fork the repo
-Make a new branch on your copy of the repo, push the changes there
-Go to your copy's github page and there should be a Create Pull Request option

**Comment by About7Sharks** [comment]
I tried to do that but i'm getting a github error.
![image](https://user-images.githubusercontent.com/30053857/116830593-5a575f00-ab79-11eb-92a8-45f873196f3e.png)
