### ISSUE TITLE
REQUEST (walletconnect) integration 

### ISSUE THREAD

**Issue by sonusseven** [vfat-tools/vfat-tools#434]
Hello,

Would you add the walletconnect ( [https://walletconnect.org/] ) as your plan for multiple wallet ?, because its really helpful when using the vfat-tools in mobile, for people who not installed Metamask on mobile.

Thanks in advance,
Regards.

**Comment by vfat-tools** [comment]
done!

**Comment by sonusseven** [comment]
Thanks so much!
