### ISSUE TITLE
Request: create link to a wallet

### ISSUE THREAD

**Issue by Philippe734** [vfat-tools/vfat-tools#447]
Hello,
Great tool, good job. Any chance to add a feature which is create a link to a wallet with a tool linked? For example, there is a tool called zapper, which is allow to create a link to a wallet. For example (not my wallet):
https://zapper.fi/fr/dashboard?address=0xfc75970a11669c571a4b8f8abeceeecffa5dc7ea
Is it possible to add the feature which allow to create a link, for example:
https://vfat.tools/bsc/pancake?address=0xfc75970a11669c571a4b8f8abeceeecffa5dc7ea

**Comment by vfat-tools** [comment]
Yes, its ?addr=0x1234
________________________________
From: Philippe734 ***@***.***>
Sent: Friday, May 7, 2021 6:33:18 PM
To: vfat-tools/vfat-tools ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [vfat-tools/vfat-tools] Request: create link to a wallet (#447)


Hello,
Great tool, good job. Any chance to add a feature which is create a link to a wallet with a tool linked? For example, there is a tool called zapper, which is allow to create a link to a wallet. For example (not my wallet):
https://zapper.fi/fr/dashboard?address=0xfc75970a11669c571a4b8f8abeceeecffa5dc7ea
Is it possible to add the feature which allow to create a link, for example:
https://vfat.tools/bsc/pancake?address=0xfc75970a11669c571a4b8f8abeceeecffa5dc7ea
