### ISSUE TITLE
[BakerySwap] Add BETH-BNB BLP and BAKE-ALICE BLP

### ISSUE THREAD

**Issue by stefanheijnen** [vfat-tools/vfat-tools#526]
Would it be possible to add these BakerySwap farms?

BETH-BNB BLP https://www.bakeryswap.org/#/eth2/ETH2MASTER/BETH-BNB%20BLP

BAKE-ALICE BLP https://www.bakeryswap.org/#/bakery/ALICE/BAKE-ALICE%20BLP

**Comment by Dimosgr** [comment]
closed with PR #559

**Comment by stefanheijnen** [comment]
Thank you for adding Alice - Bake. But I can't seem to find BETH - BNB?

**Comment by Dimosgr** [comment]
There is a problem with the calculation for the rewards so I cant do the BETH - BNB contract. Nevertheless, I will fix the links.
