### ISSUE TITLE
[MATIC DFYN LP] Wrong Pairs shown (MATIC-ETH)

### ISSUE THREAD

**Issue by samuel-tay** [vfat-tools/vfat-tools#530]
The pairs being shown in the app is WETH-WETH. I don't know how to attempt a fix, so I'm posting.. My best guess is that this function that needs to be fixed https://github.com/vfat-tools/vfat-tools/blob/244a8f390649f5f3a50346dd72bce76322d5033d/src/static/js/matic_helpers.js#L422

![image](https://user-images.githubusercontent.com/2001818/118281031-5cb5a380-b4ff-11eb-830c-de296262ac9d.png)

**Comment by vfat-tools** [comment]
I saw this yes for some reason it says WETH instead of WMATIC, haven't investigated yet though due to the backlog being a bit crowded
