### ISSUE TITLE
Please add [Fantom] - STRD finance

### ISSUE THREAD

**Issue by mmmmyah** [vfat-tools/vfat-tools#532]
Please add support for Fantom - strd.finance
https://strd.finance/

Thanks!

**Comment by mmmmyah** [comment]
If it helps, STRD is an autofarm (from bsc/heco) clone onto Fantom .. thanks

**Comment by vfat-tools** [comment]
https://vfat.tools/fantom/standard/

**Comment by mmmmyah** [comment]
that was quick... thank you!!!!
