### ISSUE TITLE
DragonBall Finance issues

### ISSUE THREAD

**Issue by CampinSam** [vfat-tools/vfat-tools#542]
The calculator for Dragonball Finance broke with their recent switch to a custom AMM. Could you guys please fix the token pricing sources so that the calculators work again.

**Comment by Dimosgr** [comment]
closed with PR #559

**Comment by CampinSam** [comment]
> closed with PR #559

I just checked, appreciate the quick fix for DBALL. Would you please fix the price for SENZU also?

**Comment by Dimosgr** [comment]
Unfortunately I cant because SENZU price is not on coingecko.
