### ISSUE TITLE
Please support frankenstein.finance on [FANTOM]

### ISSUE THREAD

**Issue by mmmmyah** [vfat-tools/vfat-tools#585]
Please support the following platform on fantom:

https://frankenstein.finance/#/farms

thanks!

**Comment by vfat-tools** [comment]
hello, i had some trouble getting info from the contracts, is there a list of them available?

**Comment by mmmmyah** [comment]
If you expand each pool there is a link to the contract as listed via ftmscan, note that ftmscan itself was undergoing some maintenance. I also found their github here https://github.com/FrankenDefi/contracts

Hope that helps - otherwise you can try asking on their telegram https://t.me/frankensteinfinance

**Comment by drop-out-dev** [comment]
Addressed in #602

**Comment by Dimosgr** [comment]
Has Added
