### ISSUE TITLE
Please add support for StakeSteak [FANTOM]

### ISSUE THREAD

**Issue by Zekz10** [vfat-tools/vfat-tools#590]
Hi vfat, 

Would you please add support for a new farm on Fantom?
Website: https://stakesteak.com/
Contracts: https://xamcrypto.gitbook.io/stak/resources/contracts

Thanks for the awesome tool you provide the defi community!

**Comment by earlofurl** [comment]
Great project trying to stabilize fUSD. Definitely add!

**Comment by mmmmyah** [comment]
+me
