### ISSUE TITLE
Add Grapeswap on BSC

### ISSUE THREAD

**Issue by lebahye** [vfat-tools/vfat-tools#829]
Hi, 

Could you please add https://grapestaking.lidia.in/# on BSC - contract 0xb699390735ed74e2d89075b300761dae34b4b36b

Twitter: https://twitter.com/GrapeSwap
Telegram Group: https://t.me/grapeswap
Grape Tools: https://grapestaking.lidia.in/

**Comment by vfat0** [comment]
this needs to be submitted via pull request due to non-standard contracts, please ask the grapeswap devs
