### ISSUE TITLE
Thoreum APR doesn't show

### ISSUE THREAD

**Issue by Tomlincoln** [vfat-tools/vfat-tools#858]
Hey, Thoreum is showing APRs like this:

`APR: Day NaN% Week NaN% Year NaN%`

Could you please check? :)

**Comment by vfat0** [comment]
this is correct, because there is no pool for the thoreum token

**Comment by Tomlincoln** [comment]
So when they add THOREUM/BNB and THOREUM/BUSD pools, it will correctly show things?

**Comment by vfat0** [comment]
it is already showing things correctly :) but it will also show them after they do yes :)

**Comment by Tomlincoln** [comment]
Thanks for the info, then I close this. :)
