### ISSUE TITLE
Valuedefi vsafe tool not calculating holdings properly

### ISSUE THREAD

**Issue by Anubian7** [vfat-tools/vfat-tools#87]
The tool appears to calculate ur position size by multiplying the number of shares you have by the price of the LP tokens.  This leads to a really dramatic undervaluation, especially for the vbswap/bnb vsafe in particular as share price has diverged so greatly from a 1 to 1 ratio with the LP token.  (atm 1 share = 1.37363 vBSWAPBNB) 
The correct method would be to calculate the number of LP tokens that those shares represent based on current shares to LP price ratio then multiply that by the price of the LP tokens.   -  An example below of pricing at current time:
1 vBSWAPWBNB = $2724.97             1 vsVbswapBNB = 1.37363 x vBSWAPBNB = $3.822,68

(sorry i didnt know how else to contact you)

**Comment by vfat-tools** [comment]
@kundark are you able to take a look at this?
