### ISSUE TITLE
Installing the Github Slack App in this Repository

### ISSUE THREAD

**Issue by abigger87** [vfat-tools/vfat-tools#902]
Hi vfat-tools team!

Opening this issue to request repository owners to install the [github slack app](https://slack.github.com/) (https://slack.github.com/) in this repository so people may subscribe to this repo in slack.

Thanks!

**Comment by vfat0** [comment]
I would need to connect it to a specific slack server I believe

**Comment by abigger87** [comment]
Apologies, wrong link - this is the Slack app for in Github https://github.com/apps/slack 
side note - as you can see the app is built by Github so I think it's reasonably secure :)

**Comment by vfat0** [comment]
Still requires a sign in to slack unfortunately

**Comment by vfat0** [comment]
however that first link, could you not just set that up on your slack anyway? since this repo is public

**Comment by abigger87** [comment]
bizarre - yes it is working now, my bad. I must have had the wrong app installed :/ Closing now, apologies again.
