### ISSUE TITLE
Please teach us how to gather the underlying data

### ISSUE THREAD

**Issue by Bruce2W** [vfat-tools/vfat-tools#913]
Would it be possible to get a short tutorial on how to manually gather such data for BSC DeFI sites?

Many thanks in advance.

**Comment by jantancelaka** [comment]
I was hoping for the same too

**Comment by vfat0** [comment]
sure happy to help but can you be more specific as to which data you are looking for? e.g. how to calculate TVL, rewards per week, APR?

**Comment by Bruce2W** [comment]
Thank you vfat0!

Perhaps it would be good to use an example. Looking at https://home.babyswap.finance/pools I would like to understand how to calculate the rewards per week or APR.  My experience is that the APR shown on screen is incorrect.  Being new I am uncertain how to look up the contract information to get started on that. 

This is the BscScan link for the pool. 

My limited understanding is that you are pulling data from the wallet to DeFi interaction which I am uncertain how to do.

**Comment by vfat0** [comment]
That particular contract seems very risky, the rugdoc review seems to agree. Either way, to get the rewards per week for pool 0 starting here: https://bscscan.com/address/0xdfAa0e08e357dB0153927C7EaBB492d1F60aC730#readContract 
`cakePerBlock` = 12000000000000000000 / 1e18 = 12 (cake here means BABY), so rewards are 12 BABY per block for all pools combined
`totalAllocPoint` = 159
`poolInfo(0)` -> `allocPoint` = 53
So pool 0 pays 12 * 53 / 159 = 4 BABY per block
BSC block average time is 3 seconds, so a week has 604800 seconds / 3 sec/block = 201600 blocks
Therefore pool 0 pays 4 * 201600 = 806400 BABY per week, current price $0.116 so $93,542.40 rewards per week or multiply that by 52 to get $4,864,204.80 per year.
To calculate APR we also need the pool's TVL. We check `poolInfo(0)` and see the `lpToken` in this case is BABY itself. We check how much BABY there is in this masterchef contract by going to https://bscscan.com/address/0x53e562b9b7e5e94b81f10e96ee70ad06df3d2657#readContract and calling `balanceOf(0xdfAa0e08e357dB0153927C7EaBB492d1F60aC730)`. This is currently 22321479403103514241570560 / 1e18 = 22321479 tokens or multiply that by the $0.116 price to get $2,589,291.61 TVL.
So finally the APR for pool 0 is equal to yearly rewards divided by TVL:
$4,864,204.80 / $2,589,291.61 = 1.8786 or 187.86%

**Comment by Bruce2W** [comment]
Thank you, that was exactly what I needed.

One last question, is it possible to query how much investment a wallet has in a pool through bscscan or otherwise?

**Comment by vfat0** [comment]
Yes use the `userInfo` function in https://bscscan.com/address/0xdfAa0e08e357dB0153927C7EaBB492d1F60aC730#readContract entering the pool number and the address.
