### ISSUE TITLE
BTD (BTS/BoltTrueShare) Broken. Incorrect CoinGecko ID

### ISSUE THREAD

**Issue by reed-jones** [vfat-tools/vfat-tools#93]
I believe coingecko updated the id for BatTrueShare -> Bolt True Share and its currently breaking the page on the BTS price lookup, current api call returns `{}` with the id `bat-true-share` updating the id results in having the proper usd returned

`https://api.coingecko.com/api/v3/simple/price?ids=bat-true-share&vs_currencies=usd` <- broken
`https://api.coingecko.com/api/v3/simple/price?ids=bolt-true-share&vs_currencies=usd` <- works

**Comment by vfat-tools** [comment]
thank you I've applied the fix!
