### ISSUE TITLE
sort BSC page by alphabet

### ISSUE THREAD

**Issue by kundark** [vfat-tools/vfat-tools#97]
sort projects in this page by alphabet
https://vfat.tools/bsc

**Comment by vfat-tools** [comment]
the issue with alphabetical sorting is that it won't be easy to spot new projects at the end, I agree it is a bit messy though

**Comment by kundark** [comment]
force new projects follow alphabet order as well

**Comment by vfat-tools** [comment]
my point is currently a new project is always added at the bottom. people who refresh the index page can then find the new ones immediately. if they are put in the middle of the page alphabetically, they would just get lost
________________________________
