### ISSUE TITLE
#request add https://www.bullrun.finance/

### ISSUE THREAD

**Issue by JakeDinas** [vfat-tools/vfat-tools#997]
Hi, I found a new project, could you add it? They are in 3 networks, BSC, Polygon and Fantom. They are audited by Hacken.
Web: https://www.bullrun.finance/
Contracts: https://github.com/BullRunFinance/contracts
Gitbook: https://bullrunfinance.gitbook.io/bullrun-finance
Telegram: https://t.me/BullRunFinance

**Comment by vfat0** [comment]
done

**Comment by JakeDinas** [comment]
Thank you!!
